[project]
name = "data-dashboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.3"
dependencies = [
    "reflex>=0.8.11",
    "pandas>=2.0.0",
    "faker>=25.0.0",
    "duckdb>=1.4.0",
]
